// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnAQs85hvqEx9YHuAnPnMNh__SWYeQ1y4',
    appId: '1:674027985114:web:3bb321e9cb14c375ce6de3',
    messagingSenderId: '674027985114',
    projectId: 'rainguard-app',
    authDomain: 'rainguard-app.firebaseapp.com',
    storageBucket: 'rainguard-app.firebasestorage.app',
    measurementId: 'G-2873V8K9D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4o4_M-VZkPUOnCJfDDojwJ1AGQ57euVM',
    appId: '1:674027985114:android:2d562627f986caf7ce6de3',
    messagingSenderId: '674027985114',
    projectId: 'rainguard-app',
    storageBucket: 'rainguard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQDdwme8M2Yk8ELrCKwZo0tmydPZ_Mtg',
    appId: '1:674027985114:ios:d6c20f6d9db495aece6de3',
    messagingSenderId: '674027985114',
    projectId: 'rainguard-app',
    storageBucket: 'rainguard-app.firebasestorage.app',
    iosBundleId: 'com.example.rainguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTQDdwme8M2Yk8ELrCKwZo0tmydPZ_Mtg',
    appId: '1:674027985114:ios:d6c20f6d9db495aece6de3',
    messagingSenderId: '674027985114',
    projectId: 'rainguard-app',
    storageBucket: 'rainguard-app.firebasestorage.app',
    iosBundleId: 'com.example.rainguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnAQs85hvqEx9YHuAnPnMNh__SWYeQ1y4',
    appId: '1:674027985114:web:77cc7d2d0bb16a2cce6de3',
    messagingSenderId: '674027985114',
    projectId: 'rainguard-app',
    authDomain: 'rainguard-app.firebaseapp.com',
    storageBucket: 'rainguard-app.firebasestorage.app',
    measurementId: 'G-ZTSDFQYM4G',
  );

}